### ISSUE TITLE
Kernel 5.15 on Pi 4 no longer able to make

### ISSUE THREAD

**Issue by neosaadmin** [fastoe/RTL8811CU_for_Raspbian#10]
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.15.26-v7l+/build M=/home/pi/RTL8811CU_for_Raspbian  modules
make[1]: Entering directory '/home/pi/linux-db4fcc7bd0fc08a9228a81919af21a68d38826b7'
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_cmd.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_security.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_debug.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_io.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_ioctl_query.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_ioctl_set.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_ieee80211.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_mlme.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_mlme_ext.o
/home/pi/RTL8811CU_for_Raspbian/core/rtw_mlme_ext.c: In function ‘rtw_txpwr_init_regd’:
/home/pi/RTL8811CU_for_Raspbian/core/rtw_mlme_ext.c:260:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
   if (rfctl->regd_name)
      ^
/home/pi/RTL8811CU_for_Raspbian/core/rtw_mlme_ext.c:263:2: note: here
  default:
  ^~~~~~~
/home/pi/RTL8811CU_for_Raspbian/core/rtw_mlme_ext.c: In function ‘mgt_dispatcher’:
/home/pi/RTL8811CU_for_Raspbian/core/rtw_mlme_ext.c:1350:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
    ptable->func = &OnAuthClient;
    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/home/pi/RTL8811CU_for_Raspbian/core/rtw_mlme_ext.c:1352:2: note: here
  case WIFI_ASSOCREQ:
  ^~~~
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_mi.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_wlan_util.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_vht.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_pwrctrl.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_rf.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_chplan.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_recv.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_sta_mgt.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_ap.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/mesh/rtw_mesh.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_xmit.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_p2p.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_rson.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_tdls.o
  CC [M]  /home/pi/RTL8811CU_for_Raspbian/core/rtw_br_ext.o
/home/pi/RTL8811CU_for_Raspbian/core/rtw_br_ext.c:20:11: fatal error: net/ipx.h: No such file or directory
  #include <net/ipx.h>
           ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:277: /home/pi/RTL8811CU_for_Raspbian/core/rtw_br_ext.o] Error 1
make[1]: *** [Makefile:1868: /home/pi/RTL8811CU_for_Raspbian] Error 2
make[1]: Leaving directory '/home/pi/linux-db4fcc7bd0fc08a9228a81919af21a68d38826b7'
make: *** [Makefile:2374: modules] Error 2




Attempting to remake the driver after an incidental Pi4 kernel upgrade. Unable to. Kernel 5.15 Pi4 Pi OS 32Bit.

**Comment by tjura** [comment]
Same issue. I found workaround with other drivers:
https://github.com/morrownr/8821cu-20210118

sudo bash [ARM_RPI.sh](https://github.com/morrownr/8821cu-20210118/blob/main/ARM_RPI.sh)
sudo bash [install-driver.sh](https://github.com/morrownr/8821cu-20210118/blob/main/install-driver.sh)

**Comment by dariosalvi78** [comment]
same issue here, but using https://github.com/morrownr/8821cu-20210118 has worked.

**Comment by fastoe** [comment]
For RPi kernel 5.11 or later, please clone the v5.8.7 branch.
```
sudo apt install -y bc git dkms build-essential raspberrypi-kernel-headers
git clone -b v5.8.7 https://github.com/fastoe/RTL8811CU_for_Raspbian
cd RTL8811CU_for_Raspbian
make
sudo make install
sudo modprobe 8821cu
sudo reboot
```
