### ISSUE TITLE
some warnings when "Make"

### ISSUE THREAD

**Issue by jonas740** [fastoe/RTL8811CU_for_Raspbian#2]
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_write_reg’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:46:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_read_reg’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:132:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_write_rf’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:266:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_read_rf’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:308:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_rate’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:413:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_channel’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:463:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_ch_offset’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:490:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_bandwidth’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:517:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_txpower_index’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:550:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_txpower’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:596:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_ant_tx’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:634:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_ant_rx’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:682:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_disable_bt_coexist’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:862:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8 input[wrqu->data.length + 1];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_arx’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:900:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_pwrtrk’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:1085:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_psd’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:1123:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_dump’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:1244:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_phypara’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:1268:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_SetRFPath’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:1294:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_switch_rf_path’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:1345:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_QueryDrv’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:1394:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->data.length];
  ^~~~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_PwrCtlDM’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:1423:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_hwtx’:
/home/pi/RTL8811CU_for_Raspbian/os_dep/linux/ioctl_mp.c:2073:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->data.length];
  ^~

**Comment by fastoe** [comment]
This is just some warning messages, no compilation errors.

**Comment by kawaii-ghost** [comment]
Mine just patching with 1024 bytes or 128 bytes

**Comment by kawaii-ghost** [comment]
Mine just patching with 1024 bytes or 128 bytes
