### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by sp1d3rino** [fastoe/RTL8811CU_for_Raspbian#4]
gcc: error: -mfloat-abi=soft and -mfloat-abi=hard may not be used together

└─# make
make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.19.127-Re4son-v7+/build M=/home/spi/RTL8811CU_for_Raspbian  modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.127-Re4son-v7+'
  CC [M]  /home/spi/RTL8811CU_for_Raspbian/core/rtw_cmd.o
gcc: error: -mfloat-abi=soft and -mfloat-abi=hard may not be used together
make[2]: *** [scripts/Makefile.build:304: /home/spi/RTL8811CU_for_Raspbian/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1527: _module_/home/spi/RTL8811CU_for_Raspbian] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.127-Re4son-v7+'
make: *** [Makefile:2214: modules] Error 2

any idea?

**Comment by ahmed-elsaharti** [comment]
The bottom part of the readme covers this i think 
https://github.com/fastoe/RTL8811CU_for_Raspbian/blob/master/README.md

**Comment by fastoe** [comment]
run the rpi-source command to install the kernel headers for kernel:
```
sudo apt install -y bc git flex bison libssl-dev libncurses5-dev
sudo wget https://raw.githubusercontent.com/RPi-Distro/rpi-source/master/rpi-source -O /usr/local/bin/rpi-source && sudo chmod +x /usr/local/bin/rpi-source && /usr/local/bin/rpi-source -q --tag-update
rpi-source
```
then, re-make again.
